
export class RoutePath {
  private constructor() {
  }

  static readonly AreaPage = 'pages/convert/LengthPage';
  static readonly BMIPage = 'pages/convert/LengthPage';
  static readonly LengthPage = 'pages/convert/LengthPage';
  static readonly NumberPage = 'pages/convert/LengthPage';
  static readonly SpeedPage = 'pages/convert/LengthPage';
  static readonly TimePage = 'pages/convert/LengthPage';
  static readonly WeightPage = 'pages/convert/LengthPage';
}